### ISSUE TITLE
Pre-Live Checklist

### ISSUE THREAD

**Issue by adamamyl** [okfn/ckanext-glasgow#103]
Before Go-Live, the following things need to be sorted -- 
## Infrastructure
- [ ] Drop TTLs on ?data.glasgow.gov.uk
- [ ] Sort out DNS
- [ ] Sort out SSL certificates
- [ ] Schedule time to build go-live plan (Glasgow, OKF, Microsoft)
## Extensions
- [ ] Google Analytics set-up (UA- string needed)
- [ ] Disqus set-up (account details)
- [ ] Themeing (being done by Glasgow) QA'd
## Machines
- [ ] Frontends commissioned
- [ ] Backends commissioned
## Setup
- [ ] Set-up user accounts
- [ ] Data import / harvest
## Testing
- [ ] Load testing
- [ ] Pen testing
## Documentation
- [ ] How to install (via playbook)
- [ ] Extensions / Bespoke development
## Press
- [ ] Work out press release strategy for launch
## Launch
- [ ] Discussion / Briefing on launch; soft/hard?
## EC Pre-reqs
- [ ] endpoints/redirects for auth set-up

**Comment by adamamyl** [comment]
@stevenlivz @Nithyavasudevan : first thoughts on the checklist for things to do pre-go-live; both of you should be able to edit this, or add more.
